### ISSUE TITLE
Issue while running webpack-watch-production

### ISSUE THREAD

**Issue by RajuKottedi** [damienbod/AngularWebpackVisualStudio#100]
ERROR in ./aot/angularApp/app/app.component.ngfactory.ts
Module not found: Error: Can't resolve './app.component.scss.ngstyle'

**Comment by robisim74** [comment]
Please provide the necessary information:
- Are you using the latest webpack configuration? https://github.com/damienbod/AngularWebpackVisualStudio/blob/master/src/AngularWebpackVisualStudio/config/webpack.prod.js
- Did you update webpack with the name of your Angular app? (I saw `projectXapps`)
- Is your scss file empty or full?

Thanks

**Comment by RajuKottedi** [comment]
yes i updated webpack.prod.js to latest and updated the paths as well with my Angular app. 
scss file is not empty.

Thanks

**Comment by robisim74** [comment]
Please, can you post your `webpack.prod.js`?

**Comment by RajuKottedi** [comment]
`const path = require('path');

const webpack = require('webpack');

const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ngToolsWebpack = require('@ngtools/webpack');
const helpers = require('./webpack.helpers');
const ROOT = path.resolve(__dirname, '..');

console.log('@@@@@@@@@ USING PRODUCTION @@@@@@@@@@@@@@@');

module.exports = {

    entry: {
        'vendor': './projectXApps/vendor.ts',
        'polyfills': './projectXApps/polyfills.ts',
        'app': './projectXApps/main-aot.ts' // AoT compilation
    },

    output: {
        path: ROOT + '/wwwroot/',
        filename: 'dist/[name].bundle.js',
        chunkFilename: 'dist/[id].chunk.js',
        publicPath: '/'
    },

    resolve: {
        extensions: ['.ts', '.js', '.json']
    },

    devServer: {
        historyApiFallback: true,
        stats: 'minimal',
        outputPath: path.join(ROOT, 'wwwroot/')
    },

    module: {
        rules: [
            {
                test: /\.ts$/,
                use: '@ngtools/webpack'
            },
            {
                test: /\.(png|jpg|gif|woff|woff2|ttf|svg|eot)$/,
                use: 'file-loader?name=assets/[name]-[hash:6].[ext]'
            },
            {
                test: /favicon.ico$/,
                use: 'file-loader?name=/[name].[ext]'
            },
            {
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            },
            {
                test: /\.scss$/,
                include: path.join(ROOT, 'projectXApps/styles'),
                use: [
                    'style-loader', 
                    'css-loader', 
                    'sass-loader'
                ]
            },
            {
                test: /\.scss$/,
                exclude: path.join(ROOT, 'projectXApps/styles'),
                use: [
                     'raw-loader',
                     'sass-loader'
                 ]
            },
            {
                test: /\.html$/,
                use: 'raw-loader'
            }
        ],
        exprContextCritical: false
    },

    plugins: [
        new ngToolsWebpack.AotPlugin({
            tsConfigPath: './tsconfig-aot.json'
        }),
        new CleanWebpackPlugin(
            [
                './wwwroot/dist',
                './wwwroot/assets'
            ],
            { root: ROOT }
        ),
        new webpack.NoEmitOnErrorsPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            },
            output: {
                comments: false
            },
            sourceMap: false
        }),
        new webpack.optimize.CommonsChunkPlugin(
            {
                name: ['vendor', 'polyfills']
            }),

        // new HtmlWebpackPlugin({
        //     filename: 'Index.cshtml',
        //     inject: 'body',
        //     template: '../ProjectX/Views/Home/Index.cshtml'
        // }),

        new CopyWebpackPlugin([
            { from: './projectXApps/images/*.*', to: 'assets/', flatten: true }
        ])
    ]
};

`

**Comment by robisim74** [comment]
It seems correct. Try to check also the `tsconfig-aot.json`:  `entryModule`, and that you have `styleUrls: ['./app.component.scss'],` in your app.component.

**Comment by RajuKottedi** [comment]
i checked both files both are same except one thing i am using double quotes with styleUrls.

**Comment by robisim74** [comment]
Just one question: before customizing, did you try to launch this app as-is? Did it work?

Unfortunately I can not reproduce the error.

**Comment by RajuKottedi** [comment]
yes it was working fine. After commenting the styleUrls its working fine.

**Comment by robisim74** [comment]
If you can (if it is not a confidential project), create a repo and I will give it a a look. Greetings

**Comment by RajuKottedi** [comment]
i have created a sample repository. [https://github.com/RajuKottedi/sample-repo.git](url)

Thanks

**Comment by robisim74** [comment]
Let you know.

**Comment by robisim74** [comment]
Ok, I found the mistakes:
- paths `projectXApps/styles` in all your webpack files: you have `style` folder
- path `../aot/projectXapps/app/app.module.ngfactory`: you have `projectXApps` as a project

Then it works:

![image](https://user-images.githubusercontent.com/14012361/28492697-30aed644-6f08-11e7-99fb-5ffbff9fc99e.png)

Greetings

**Comment by RajuKottedi** [comment]
Thanks for your support. now its working fine.
