### ISSUE TITLE
New README

### ISSUE THREAD

**Issue by robisim74** [damienbod/AngularWebpackVisualStudio#101]
@damienbod @FabianGosebrink 

I pushed a new branch: https://github.com/damienbod/AngularWebpackVisualStudio/tree/Docs_refactoring

Changes:
- Move explanations to _docs_ folder
- New README

Please, see the new README and make also your changes.

Greetings,
Roberto

**Comment by FabianGosebrink** [comment]
On the first view: I love it. Great work. Will do a "go-deep" round soon and push changes directly.

BR & Thanks

**Comment by damienbod** [comment]
merged, thanks @robisim74
