### ISSUE TITLE
Correct approach to add plain .css files to the application

### ISSUE THREAD

**Issue by tonywr71** [damienbod/AngularWebpackVisualStudio#104]
I am integrating a third party package that contains some .css files (not .scss) and I would prefer to leave them that way. What is the correct way to add the .css files into the application?

**Comment by robisim74** [comment]
https://github.com/damienbod/AngularWebpackVisualStudio/blob/master/src/AngularWebpackVisualStudio/angularApp/vendor.ts

**Comment by tonywr71** [comment]
Ah, nice. Thanks!
