### ISSUE TITLE
/dist/polyfills.bundle.js not found

### ISSUE THREAD

**Issue by RahulSolanki1487** [damienbod/AngularWebpackVisualStudio#105]
when i build application using build dev command it's creating all files under dist folder but when i run start command it's deleting all files from root folder and application is giving Not found error. can anyone please help me to setup this as i have to build application using this pattern.

**Comment by robisim74** [comment]
The command `npm start` uses _webpack-dev-server_, which builds the app in memory. Then it runs on `localhost:8080`

**Comment by RahulSolanki1487** [comment]
okay that worked. i'm new to this and migrating angular 1 application to 2. Appreciate your quick response.
