### ISSUE TITLE
dotnet template

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#106]
https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/

**Comment by FabianGosebrink** [comment]
Would like to look into this when I am back

Sent from mobile device
________________________________

**Comment by FabianGosebrink** [comment]
Made a branch for this. Will test a little and then submit a PR hoping for a review and further tests
