### ISSUE TITLE
karma testing without Chrome

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#107]
The karma testing requires Chrome. Some CI env. have problems with this.

**Comment by FabianGosebrink** [comment]
We can use PhantomJS instead

**Comment by michaeljota** [comment]
But Chrome is headless now, can this be used instead of PhantomJS?

**Comment by damienbod** [comment]
I think I would prefer to keep the testing as it is, can use the storage also in the tests. Need to read up more first.

**Comment by FabianGosebrink** [comment]
Improved testing with https://github.com/damienbod/AngularWebpackVisualStudio/commit/852b590208aee2f55510570bf0671f9399b6eb82 ; closing this now
