### ISSUE TITLE
Launch from VS 2017, debug js,ts and cs files

### ISSUE THREAD

**Issue by kk4fun** [damienbod/AngularWebpackVisualStudio#109]
Hi, nice template, but there's a question:
How can I launch project based on this template from VS 2017 with debugging?
Something like here https://github.com/aspnet/JavaScriptServices
Here I can press IIS button and get app launched in debug mode, so i can put breakpoints etc.
Thanks.

**Comment by damienbod** [comment]
Hi @kk4fun 

Yes, I debug using Chrome inside VS2017

**Comment by kk4fun** [comment]
Hmm, so how can i do it? If i just run from VS IIS it just launch server, not client part.

**Comment by damienbod** [comment]
In VS2017, click the black arrow on the Start button inside visual studio and switch the Web browser to chrome

**Comment by kk4fun** [comment]
Ofcource i tried it :)
it just launched server part http://localhost:5000/index.html 
but no client in VS debug mode :(
client in template on 8080 port
Question is , how can i do it ?

**Comment by FabianGosebrink** [comment]
You would debug the client-side files in Chrome as they are loaded and executed in Chrome. Have you tried that? BR
