### ISSUE TITLE
Browser Link query

### ISSUE THREAD

**Issue by chetski** [damienbod/AngularWebpackVisualStudio#112]
This template is working fine and is close to what I'm looking for. Just wandering if anyone has got  auto refreshing the browser after editing working via Browser Link in VS2017. I'm currently having to hit refresh (F5) to see my changes which is getting to be a pain. I've googled and tried a few things including adding app.UseBrowserLink() in Startup.cs but that hasn't worked.

Anyone else having similar issues?

**Comment by FabianGosebrink** [comment]
So normally you edit the client side files and the webpack-dev-server is responsible for refreshing. Is that what youre looking for?

**Comment by chetski** [comment]
My understanding was that as we are running .NET WepAPI and Angular from the same project they are both being hosted by IIS (or IIS Express). Yes I would like to be able to edit the client side files and I'm seeing the javascript task runner (within VS2017) rebuild the client side when I make a change but I'm having to hit refresh in the browser to see the changes. 

ps. I'm starting my debug session using VS2017 (F5) which is launching chrome with my Angular app loaded as well as starting the WebAPI backend. Thus I'm able to debug both front end and back end which is great - its just the refresh issue.

**Comment by FabianGosebrink** [comment]
Ah you are starting it via the Play Button in VS? Well you should always seperate client side and server side development. VS is not a Typescript editor. So run the package with `npm start` to have the refreshing in the browser.

**Comment by chetski** [comment]
OK - I think I may have misunderstood the point of this seeder project.  I thought one of the benefits of having both the server API and the angular client app in the same project was that you could author, debug & deploy using Visual Studio (BTW, which I can apart from this irritating little issue!).

Can I just ask how you develop and debug then please? e.g. do you use VS for the server WebAPI editing and running (via IIS Express) and then another editor for editing the client side files and running the client side using npm start (via webpack-dev-server)? Wouldn't this mean that you have 2 web servers running and have unnecessary CORS issues (which I can see have been addressed in Startup.cs). Also, when you deploy I presume both client and server are deployed to IIS? But are they separate websites or deployed to the same site? Thanks

**Comment by FabianGosebrink** [comment]
Hey @chetski ,

one of the benefits is exactly what you pointed out: Having everything in one project and doing it from there. Sometimes this can be everything you want but normally you would seperate the client side from the server side as this is what a API (WebAPI in this case) is for. We designed this project here that you can easily move the client part to a different project, which you should when you get into production for several reasons. Maybe you want to switch server side technology from ASP.NET Core WebAPI to e.g. node. Or you have Mac Devs in your frontend-team which are using Macbooks and need VSCode or any editor to work with you. Also think of scaling back- and frontend, or the build-tools which are completely different. 
You then can deploy your frontend to Server A and Backend to Server B. SO you can consume the backend from another application without serving your complete frontend.

Distributed systems nowadays are better seperated. But most devs are "unsure" about using different tools. So we created this template to give an overview about all the things but for prod it should better be seperated like here

**Comment by chetski** [comment]
Thanks @FabianGosebrink - completely agree with your points esp. from a separation of concerns perspective. I think I was trying to avoid enabling CORS support on the API esp. when (in most cases) the only consumer of the API is the clientApp which will typically be on the same server/IIS. 

I'll close this ticket and take a look at your other templates :)

**Comment by FabianGosebrink** [comment]
Thank you. I am currently rearrangin some things. On the weekend I will divide this repo https://github.com/FabianGosebrink/ASPNET-ASPNETCore-Angular-Ngrx/ to an Angular/Ngrx & ASP.NET Core and an AngularJS with ASP.NET. So don't be confused :)

BR

**Comment by FabianGosebrink** [comment]
*updated link*
