### ISSUE TITLE
Issue With VS2017

### ISSUE THREAD

**Issue by SkeletonSkelettron** [damienbod/AngularWebpackVisualStudio#114]
When I run project from VS2017, app fails to open, it gives following image:
![image](https://user-images.githubusercontent.com/26940527/30775163-bd2a4bd0-a09f-11e7-8557-71312df26972.png)

then I build it with webpack and app runs. but there is no HRM in VS2017,
also when I run again, it gives same error
When I update code and clear cache, there is old version of app, until i run webpack.
any suggestions?
Thanks.

**Comment by FabianGosebrink** [comment]
Does this problem still exist?

**Comment by SkeletonSkelettron** [comment]
No
Thanks

**Comment by SkeletonSkelettron** [comment]
but there is no HMR though

**Comment by damienbod** [comment]
@SkeletonSkelettron npm start is the cmd for HMR. 

Greetings Damien

**Comment by FabianGosebrink** [comment]
Did that tip help you? @SkeletonSkelettron

**Comment by SkeletonSkelettron** [comment]
Yes fabian, 
thank to you all very much :)
