### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#118]

**Comment by damienbod** [comment]
https://github.com/damienbod/AngularWebpackVisualStudio/tree/dev_angular5

**Comment by damienbod** [comment]
It's building now 414 kb
Removed the ngtools and did a platform build which I think has the AOT stuff automatically

Very rough at present, a lot to clean up

- main.ts, main-aot.ts
- tsconfig and maybe tsconfig-aot is no longer required
- production build ...
- docs

**Comment by robisim74** [comment]
@damienbod Where you read that _AOT stuff automatically_? Angular CLI has AOT by default since 1.5.0-rc.4, through `@ngtools/webpack`: https://github.com/angular/angular-cli/releases
Removing `@ngtools/webpack` and factory files, I think you are also building _prod_  using JiT compiler.

**Comment by damienbod** [comment]
yes, new to Add the AOT stuff again, a lot seems to have changed here

**Comment by damienbod** [comment]
thanks, good idea

**Comment by damienbod** [comment]
Plan: Release as soon as Angular 5 is released and all npm install warnings are fixed

Version 3.0.0

Open: 
- docs
- validation that we're doing it right
- size validation
- clean up

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink 

I think the angular 5 branch is ready to go, have I missed anything, or do you think it needs improvements?

We can release, merge to the master once Angular 5 is released.

**Comment by robisim74** [comment]
I disagree. the branch is incorrect. By removing the `tsconfig-aot` and the factory file from `main-aot,` you are building the app as if it was compiled with the tsc compiler.

**Comment by damienbod** [comment]
Ok, thanks, didn't know that, branch is not ready then

**Comment by damienbod** [comment]
@robisim74 I added the tsconfig-aot again, but when I add the factory file back to the main-aot, the build breaks with the new angular.

Greetings Damien

**Comment by robisim74** [comment]
I updated this sample: https://github.com/robisim74/angular-l10n-sample

_genDir_ is no longer supported, and _aot_ folder is no longer generated (unless you set _outDir_ in ts options)

**Comment by FabianGosebrink** [comment]
Hey @robisim74 , thank you for pointing that out. So the "only" advantage is, that the aot folder does not get generated anymore?
BR

**Comment by robisim74** [comment]
The advantage of the new plugin is that it could also be used in dev mode (like Angular CLI).

**Comment by FabianGosebrink** [comment]
Just thinking out loud: Is there a chance to get rid of the two (dev/prod) webpack.configs then and work with the provideplugin instead, providing the current environment to the application?

**Comment by robisim74** [comment]
The two webpack config are necessary, as there are obviously different configurations between dev and prod in real apps. It's not just a matter of aot compilation.

**Comment by damienbod** [comment]
I like the 2 configs as well

so we just need to remove the 2 unused properties and the 2 builds work. We don't use the aot for dev at present, but then the HMR works

**Comment by damienbod** [comment]
fixed the main-aot.ts to use the ngfactory

@robisim74 Why do we use the AppModuleNgFactory here? 

Also after switching to the AppModuleNgFactory, the bundle increased in size to 437 KB, using AppModule = 417 KB

**Comment by robisim74** [comment]
_AppModuleNgFactory_ is the entry module generated by _ngc_ compiler. In this way you use the _aot_ compiled files.

Compiled bundles have always been bigger, but for faster execution.

**Comment by damienbod** [comment]
Typescript 2.6.1
Could not find implementations for the following rules specified in the configuration:
    no-access-missing-member
    templates-use-public
    invoke-injectable

**Comment by damienbod** [comment]
I added the these to the tsconfig files. 
// "noUnusedLocals": true,
// "noUnusedParameters": true,

Agree or should we comment them in? I would prefer these as warnings, but errors are also ok

@robisim74 @FabianGosebrink

**Comment by damienbod** [comment]
merge to master?

**Comment by FabianGosebrink** [comment]
Angular 5 is out, lets merge the branch to master
