### ISSUE TITLE
Configuring webpack to use lettable operators

### ISSUE THREAD

**Issue by dushkostanoeski** [damienbod/AngularWebpackVisualStudio#119]
I probably wouldn't be able to set up a Core + Angular if it wasn't for this repository :)

I have a question about configuring webpack to be able to use the new lettable operators in rxjs 5.5. As per [this](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md#build-and-treeshaking) I added the following code:
```
const rxPaths = require('rxjs/_esm5/path-mapping');
...

  resolve: {
        extensions: ['.ts', '.js', '.json'],
        alias: rxPaths()
    },

....

  plugins: [
        new webpack.optimize.ModuleConcatenationPlugin(),
        new webpack.optimize.CommonsChunkPlugin({ name: ['vendor', 'polyfills'] }),
    ...
```

to the `webpack.dev.js` file. Webpack isn't my strong suite, so was wondering if that's all it takes, or some other configuration is needed.

**Comment by FabianGosebrink** [comment]
IIRC you dont need to change anything using the lettable operators. Just use them in your files...or did you get an error while trying it?

**Comment by dushkostanoeski** [comment]
Nope, no errors, just a bit of optimisation.  Without the webpack

**Comment by FabianGosebrink** [comment]
Zes, but you can also avoid using the barrel and use

```import { map } from 'rxjs/operators/map';
import { filter } from 'rxjs/operators/filter';```

instead.

Will have a look at this at the weekend. Thx for pointing out!

**Comment by FabianGosebrink** [comment]
Yepp, just tested. Bundles are a bit smaller. Thanks :) We will add that soon!

**Comment by dushkostanoeski** [comment]
I made a PR, but can't push it for some reason. Also I can migrate the project to Bootstrap 4 if you'd like.

**Comment by FabianGosebrink** [comment]
One topic per thread pls. :) does that help?

https://damienbod.com/2016/11/25/contributing-to-oss-projects-on-github-using-fork-and-upstreams/

**Comment by dushkostanoeski** [comment]
That does help, and will post a new issue once I get this one sorted out :)

**Comment by FabianGosebrink** [comment]
Great, thank you.
