### ISSUE TITLE
req is not defined error from polyfills.js bundle when using build-production

### ISSUE THREAD

**Issue by chetski** [damienbod/AngularWebpackVisualStudio#125]
When using "build-production" the polyfills.js bundle produces the following javascript error: "Uncaught ReferenceError: req is not defined".

![untitled](https://user-images.githubusercontent.com/29078867/32435105-f8ade2c0-c2d7-11e7-9dee-f7661a34a251.png)

A quick google implied this is a problem with the output from UglifyJS but didn't manage to find a solution. 

Anyone else seeing the issue and/or have a solution?

**Comment by FabianGosebrink** [comment]
can not confirm this. Just did a clean install. Have you modified anything? BR

**Comment by chetski** [comment]
I have made some mods (e.g.  upgraded to bootstrap4) but wouldn't have thought it would cause the issue. I'll double check with a clean install and get back to you.

**Comment by chetski** [comment]
Doing a clean install of the template and its fine so it must be something I did but I have no idea.
Also, I deleted my node_modules and did npm install again and the problem has gone away as per this 
[https://stackoverflow.com/questions/47149671/angular-5-uncaught-referenceerror-req-is-not-defined](SO thread). 
Happy to close the issue.
