### ISSUE TITLE
Adding timestamp to the development script

### ISSUE THREAD

**Issue by dushkostanoeski** [damienbod/AngularWebpackVisualStudio#127]
When running `watch-webpack-dev` I almost always refresh before the new scripts compile. My console window is't that high, the last few lines are almost always the same, so adding a timestamp would help quite a lot.
```
 function() {
            this.plugin('watch-run',
                function(watching, callback) {
                    console.log('\x1b[33m%s\x1b[0m', `Begin compile at ${(new Date()).toTimeString()}`);
                    callback();
                });
        },
```
I found that bit of code [here](https://gist.github.com/neko-fire/6372ab712640ae7e0d5242fdf92c5e0b) and changed the format to output the time only.

**Comment by FabianGosebrink** [comment]
Do you want to create a PR for this?
