### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by Gope** [damienbod/AngularWebpackVisualStudio#13]
Hello and let me thank you first for this really helpfull template!

I am facing severe problems at the moment integrating Bootstrap 4 into this template. I tried different installation instructions from GitHub and the web but was not successfull. Did you try or manage to do so?!

Best regards
Gope

**Comment by damienbod** [comment]
Hi @Gope 

I haven't tried yet, sounds like a really good idea, I still use bootstrap 3 everywhere...

Greetings Damien

**Comment by damienbod** [comment]
@FabianGosebrink @robisim74 Should we switch to the new bootstrap?

**Comment by FabianGosebrink** [comment]
Bootstrap 4 is currently in alpha-stadium (Currently v4.0.0-alpha.6). I would like to switch when its released.

**Comment by robisim74** [comment]
I agree.

**Comment by chrisj-skinner** [comment]
Do you have a bootstrap branch / version of this currently using something like [bootstrap-loader](https://github.com/shakacode/bootstrap-loader). (not just including the fully fledged styles file in the head).

**Comment by Trapulo** [comment]
include bootstratp 4 and tether in package.json,
then in vendor.ts import "tether/dist/js/tether.min";
add this to webpacks:  new webpack.ProvidePlugin({
                jQuery: 'jquery',
                $: 'jquery',
                jquery: 'jquery',
                "Tether": 'tether'
            })

**Comment by FabianGosebrink** [comment]
Find latest information here https://github.com/damienbod/AngularWebpackVisualStudio/pull/123

**Comment by dushkostanoeski** [comment]
Bootstrap v4.0.0 is out. I updated my PR so it can be merged if all checks out.

**Comment by damienbod** [comment]
@dushkostanoeski thank you!
