### ISSUE TITLE
AppModuleNgFactory

### ISSUE THREAD

**Issue by eretontali** [damienbod/AngularWebpackVisualStudio#133]
The  "{ AppModuleNgFactory } from './app/app.module.ngfactory'"  doesnt exist in main-aot.ts file

**Comment by FabianGosebrink** [comment]
Have you done a fresh npm install? Give us a bit more information - help us to help you :)

**Comment by lanovoy** [comment]
I saw that one error when there were other errors with the build. Once those were fixed, this one did go away as well.

**Comment by lanovoy** [comment]
app.module.ngfactory is created automatically by the build. If it doesn't exists it only means that there was some other error which prevented it from getting created.
