### ISSUE TITLE
Style Broken in production

### ISSUE THREAD

**Issue by Bushira23** [damienbod/AngularWebpackVisualStudio#134]
Hi,

My application's CSS work fine in development environment. However, when I compile in production, all CSS styles are not applied. Could you please assist?

Kind Regards,
Rachidi

**Comment by Bushira23** [comment]
Hello Damien,

I do trust you are well. Is there any feedback pertaining to this issue?

Kind Regards,
Rachidi

**Comment by Bushira23** [comment]
Hello Damien,

Any update?

Kind Regards,
Rachidi

**Comment by FabianGosebrink** [comment]
I just did a fresh installation `npm install` and cant reproduce the issue. Do you still have it after an update of the sources, a deletion of the `npm_modules`-folder, a deletion of the package-lock.json and a clean `npm install`?

Cheers

**Comment by Bushira23** [comment]
Hi Fabian,

Thank for your reply. I have deleted node_modules folder and then re-installed npm as suggested by you. However, I can still observe the issue on my end. For reference, I have attached the config files used for production on my end.
Could you please assist in debugging this issue or tell me what is causing this behaviour in production?

Kind Regards,
Rachidi


[production_config_files.zip](https://github.com/damienbod/AngularWebpackVisualStudio/files/1618005/production_config_files.zip)

**Comment by FabianGosebrink** [comment]
Did you change the files in any kind of way?

**Comment by Bushira23** [comment]
Hi Fabien,

The only changes I made to your files are the following:
1) Added css settings since I have a styles.css and not styles.scss.
2) Moved my vendors css files to my styles.css instead of vendor.ts.

Please find attached both sets of files before and after modification.
Thanking you in advanced for your help.

Kind Regards,
Rachidi

[production_config_files_modified.zip](https://github.com/damienbod/AngularWebpackVisualStudio/files/1621617/production_config_files_modified.zip)
[production_config_files_original.zip](https://github.com/damienbod/AngularWebpackVisualStudio/files/1621618/production_config_files_original.zip)

**Comment by FabianGosebrink** [comment]
So you changed the css setting and now it doesnt work anymore :) I always assumed that you had problems with our template directly without any modifications. However: please make a repository on your github and I will look into it when I have time.
Cheers
