### ISSUE TITLE
Looking for the HMR specific code in the zip

### ISSUE THREAD

**Issue by dtabaka** [damienbod/AngularWebpackVisualStudio#138]
Hi, I downloaded the solution .zip and don't see the HMR specific code mentioned in the readme such as the "start": "concurrently \"webpack-dev-server --hot --inline --port 8080\" \"dotnet run\" " in the package.json and the module.hot.accept() call in the main.ts.  Unless I'm missing something.  I'm really interested in seeing a working example as I've been fighting with getting HMR to work in my VS 2017/Angular solution.  Thanks

**Comment by FabianGosebrink** [comment]
Hey, have you double checked this? I just loaded the zip and its containing the same content as the repo.

Cheers

**Comment by FabianGosebrink** [comment]
Closing this issue as it gets no reaction.
