### ISSUE TITLE
AOT setup questions

### ISSUE THREAD

**Issue by izverev-aexsoft** [damienbod/AngularWebpackVisualStudio#139]
I've tried to plug-in third-party theme which uses Angular Material.

AOT stops work, it breaks in "style-loader" with "window is not defined" errors.

I can not wrap my head around this. Look, as far as I get, AOT should not be able to work with style-loader at all, because style-loader requires DOM to insert styles and can't do its work at the server.

So it leads me to next questions: 

 1. why it works with style-loader out-of-box at AngularWebpackVisualStudio?
 2. how AOT should be set up at all? Is it true that it won't work if I reference ANY third-party module which use 'window' or 'document'?

**Comment by SaiKrishnaTej23** [comment]
Any update on this error. I am facing the same issue.

**Comment by damienbod** [comment]
Here's and example of with Material

https://github.com/damienbod/AspNetCoreAngularSignalRSecurity/tree/master/DirectMessagesAngular
