### ISSUE TITLE
Angular-cli support

### ISSUE THREAD

**Issue by ddlaat** [damienbod/AngularWebpackVisualStudio#140]
Currently it is not possible to use angular-cli with this project. Might it be a good idea to include the .angular-cli.json file? I tried to add it, but ran into some errors, possibly because of a version mismatch or something.

**Comment by robisim74** [comment]
@ddlaat Please see this issue: https://github.com/damienbod/AngularWebpackVisualStudio/issues/131

**Comment by ddlaat** [comment]
Thank you!
