### ISSUE TITLE
Install webpack-cli error

### ISSUE THREAD

**Issue by RonCass** [damienbod/AngularWebpackVisualStudio#142]
Hi Guys,
When I clone the repo, do an npm install and then an nmp start, I get an error telling me that The CLI moved into a separate package: webpack-cli. So I add webpack-cli: 2.0.12 to the package.json, do another npm install and then I get another error. I googled and and found a post about having to upgrade to Webpack 4, so I updated

"webpack": "^4.1.1",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-cli": "^2.0.12",
    "webpack-dev-server": "^3.1.1"

And now I get another error in node_modules\webpack\lib\webpack.js:162 - throw new RemovedPluginError.

And somewhat unrelated, just wanted to let you guys know I've been using your template since it first came out on every new project I start. You guys rock! :)

Update: I commented out this line 
new webpack.optimize.CommonsChunkPlugin({ name: ['vendor', 'polyfills'] })
 in the config > webpack.dev.js and I can npm start without errors. I'm sure this is not the correct way to fix the issue but now I can move forward with my new project. 

Ron C.

**Comment by damienbod** [comment]
We have updated to Angular 6 , Webpack 4
