### ISSUE TITLE
AOT Build Fail

### ISSUE THREAD

**Issue by SaiKrishnaTej23** [damienbod/AngularWebpackVisualStudio#144]
ERROR in C:/Users/VSConnect/source/Workspaces/HR-Connect/ConnectWeb/Connect/src/Connect/angularApp/main-aot.ts (4,36): Cannot find module '../aot/angularApp/app/app.module.ngfactory'.
ERROR in Could not resolve "angularApp/app/app.module" from "angularApp/app/app.module".
ERROR in C:/Users/VSConnect/source/Workspaces/HR-Connect/ConnectWeb/Connect/src/Connect/angularApp/main-aot.ts (4,36): Cannot find module '../aot/angularApp/app/app.module.ngfactory'.
ERROR in ./angularApp/main-aot.ts
Module not found: Error: Can't resolve '../aot/angularApp/app/app.module.ngfactory' in 'C:\Users\VSConnect\source\Workspaces\HR-Connect\ConnectWeb\Connect\src\Connect\angularApp'
 @ ./angularApp/

tsconfig-aot.json

{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "lib": [
      "es2015",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "entryModule": "./angularApp/app/app.module#AppModule",
    "skipMetadataEmit": true
  },
  "compileOnSave": false,
  "buildOnSave": false
}

main-aot.ts

import { enableProdMode } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';

import { AppModuleNgFactory } from '../aot/angularApp/app/app.module.ngfactory';

// Entry point for AoT compilation.
declare var System: any;
// Styles.
enableProdMode();

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);

**Comment by damienbod** [comment]
We have updated to Angular 6 , Webpack 4
