### ISSUE TITLE
Can not start project

### ISSUE THREAD

**Issue by west1989** [damienbod/AngularWebpackVisualStudio#147]
In startup file I edit this line of code

```
if (env.IsDevelopment())
{
      app.UseDeveloperExceptionPage();
      app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
       {
             HotModuleReplacement = true
        });
        app.UseBrowserLink();
        app.UseDatabaseErrorPage();
 }
```
after running project it throws an exception near 4th line (new WebpackDevMiddlewareOptions );

An error occurred while starting the application.
**AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.)**
System.Threading.Tasks.Task<TResult>.GetResultCore(bool waitCompletionNotification)

**JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.**
Newtonsoft.Json.JsonTextReader.ParseValue()

AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.)
System.Threading.Tasks.Task<TResult>.GetResultCore(bool waitCompletionNotification)
Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
Angular2WebpackVisualStudio.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
**+64.  app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions**
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter+<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

I'am using windows 10 operation system and installed this version of sdk https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.301-windows-x64-installer

**Comment by FabianGosebrink** [comment]
Can you take a look at this and try the options there? https://github.com/aspnet/JavaScriptServices/issues/430
