### ISSUE TITLE
Controller not being registered when running with webpack-dev-server

### ISSUE THREAD

**Issue by jayeshinho** [damienbod/AngularWebpackVisualStudio#148]
Hello,

I added a simple controller like below:

```
    [Route("api/[controller]")]
    public class TestController : Controller
    {
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }
    }
```
When running the application using start command in Task Runner Explorer (which uses webpack-dev-server), the controller is not registered and returns 404.

But, if I run the project using IIS express (Visual Studio debug option), the controller action correctly returns value1 and value2.

Why is the controller not being registered?

**Comment by FabianGosebrink** [comment]
Have you check if the webapi starts when using `npm start`?

**Comment by jayeshinho** [comment]
Yes, it still shows 404. 

I think I found the reason. When doing `npm start`, _webpack-dev-server_ runs at **8080** port and the `dotnet run` part of that command runs at **5000** port. I verified by posting at 5000 port, it works. But, at port 8080, it shows 404.

Is it due to `launchSettings.json` file? It sets the port at 5000?

**Comment by FabianGosebrink** [comment]
The solution is implemented to separate client and server. In a real world scenario they should be separated and deployed to two different services. So the client application on port 8080 sends requests to port 5000 where the API is running and your new controller should be answering.

**Comment by jayeshinho** [comment]
I understand. Will close the issue now.
