### ISSUE TITLE
How to add bootstrap plugins?

### ISSUE THREAD

**Issue by maksir** [damienbod/AngularWebpackVisualStudio#18]
I want to add 'eonasdan-bootstrap-datetimepicker'.
**1. package.json:**
"eonasdan-bootstrap-datetimepicker": "4.17.43",
"moment": "2.15.2",
"@types/jquery": "2.0.33",
"@types/moment": "2.13.0",
"@types/bootstrap": "3.3.32",
"@types/eonasdan-bootstrap-datetimepicker": "^4.17.22"
**2. vendor.ts:**
import 'moment';
import 'eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js';
**3. webpack.dev.js:**
resolve: {
        **alias: {
            jquery: path.join(__dirname, 'node_modules/jquery'),
            moment: path.join(__dirname, 'node_modules/moment/moment.js'),
        },**
        extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html']
    },
**4. my.component.ts:**
import { Component, OnInit } from '@angular/core';
import 'jquery';
import 'bootstrap';
import 'eonasdan-bootstrap-datetimepicker';
@Component()...
...
ngOnInit(){
$('#datepicker').datetimepicker();
}
...
and has error:
$(...).datetimepicker is not a function

**how to fix this?**

**Comment by robisim74** [comment]
Hi,

it seems a bug: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1662.

However, you can work around the problem by changing the settings in webpack (dev & prod):

```
...
    resolve: {
        alias: {
            moment: path.join(__dirname, 'node_modules/moment/moment'),
        },
        extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html']
    },
...
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        }),
...
```
It's working:

![cattura di schermata 5](https://cloud.githubusercontent.com/assets/14012361/19971362/0e2b69c6-a1df-11e6-9f2e-805af4a92273.png)

Greetings

**Comment by maksir** [comment]
Thank you! Develop mod is ok. Production mode don`t works :-(

**Comment by robisim74** [comment]
Hi,

I don't see errors in production:

![image](https://cloud.githubusercontent.com/assets/14012361/20116344/2ed79840-a5fc-11e6-9e1f-5cff797d445f.png)

Have you set also `webpack.prod.js`?

If yes, please post the error you get.

**Comment by maksir** [comment]
Sorry, more one buildProduction, and all ok.
