### ISSUE TITLE
styleUrls

### ISSUE THREAD

**Issue by Tolitech** [damienbod/AngularWebpackVisualStudio#49]
Hello.
Excellent job.
Congratulations.

Is it possible to use styleUrls in a component?
`styleUrls: ['about.component.css']`

When we use the following error occurs:
Error: Expected 'styles' to be an array of strings.

If I use:
`styleUrls: ['about.component.css'.toString()]`
Will work on JiT, but AOT compilation error will occur.

If we use:
`import './about.component.css';`

The style is not restricted to the component.
It is used on all website.

How to proceed?

Thank you.

**Comment by damienbod** [comment]
Thanks

At present I use only import with scss or css due to the problems you mentioned above.  Tried to find a way to use styleUrls which will work with JIT and AoT but found no solution.

Greetings Damien

**Comment by robisim74** [comment]
@damienbod You say right, but only for the SCSS files: CSS files should work with JiT and AoT compilation.

Regarding this error: `Error: Expected 'styles' to be an array of strings.`, see this question: https://github.com/webpack/style-loader/issues/123

About AoT compilation, we should add `angular2-template-loader` also to `webpack.prod`.

**Comment by damienbod** [comment]
@robisim74 I think so as well.

**Comment by damienbod** [comment]
fixed
example here:
https://github.com/damienbod/Angular2WebpackVisualStudio/blob/master/src/Angular2WebpackVisualStudio/angular2App/app/modules/about/components/about.component.ts

**Comment by Tolitech** [comment]
Thanks, @damienbod 

What exactly was changed?
What files? Webpack?
I'm going to test and thank you very much.

**Comment by FabianGosebrink** [comment]
@Tolitech please see the latest commit for that information:

https://github.com/damienbod/Angular2WebpackVisualStudio/commit/cc547f5fe6cc581c77a69aacd2dad48e02bdba81#diff-c765faf5fb4fe21767e5a649ebe8e7df

BR

**Comment by damienbod** [comment]
@Tolitech @robisim74 @FabianGosebrink 

production build works, but the dev build crashes. Will have to remove this until I find a solution, will create a new branch for this.

@Tolitech added a angular2-template-loader to the prod build.

**Comment by damienbod** [comment]
dev branch for this issue:
origin/cssStylesLoadingInComponent
