### ISSUE TITLE
New name for the repository

### ISSUE THREAD

**Issue by robisim74** [damienbod/AngularWebpackVisualStudio#77]
@damienbod @FabianGosebrink What do you think if we rename the repository to _AngularWebpackVisualStudio_ as the project (Angular v4 is coming)? It is not a problem because GitHub automatically redirects the old links to the new URL.

**Comment by damienbod** [comment]
great idea

**Comment by damienbod** [comment]
I will switch to angular 4 in the master , and create a 2.x branch Good?

**Comment by FabianGosebrink** [comment]
Yep, go for it!

Sent from mobile device
________________________________

**Comment by robisim74** [comment]
Great!

**Comment by damienbod** [comment]
done
