### ISSUE TITLE
AOT cannot find  module.ngfactory in production build

### ISSUE THREAD

**Issue by sharifnascenia** [damienbod/AngularWebpackVisualStudio#83]
Hi,
I am trying to build webpack in production mode. But it is showing the following compilation error 👍 

ERROR in ./angularApp/app/app.routes.ts
Module not found: Error: Can't resolve '.\..\..\aot\angularApp\app\about\about.module.ngfactory' in 'C:\Users\Dell\documents\visual studio 2015\Projects\Anguar2WebPack\src\Anguar2WebPack\angularApp\app'
 @ ./angularApp/app/app.routes.ts 5:139-212
 @ ./angularApp/app/app.module.ts
 @ ./angularApp/app/app.module.ngfactory.ts
 @ ./angularApp/main-aot.ts
 
I don't have any clue why is this happening. can any one help me about this.
Here is my main.aot.ts file:
```
import { platformBrowser } from '@angular/platform-browser';
import {AppModuleNgFactory } from './app/app.module.ngfactory';
import {AboutModuleNgFactory } from "./app/about/about.module.ngfactory";

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```
Up to this everything is ok.
 Here is my app.route.ts:

```
import { Routes, RouterModule } from '@angular/router';

export const routes: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    {
        path: 'about', loadChildren: './about/about.module#AboutModule',
    }
];

export const AppRoutes = RouterModule.forRoot(routes);
```

Here  the problem causing the "./about/about.module#AboutModule"
it cannot load the AboutModule and getting the above error.

**Comment by keithmuk** [comment]
Open tsconfig-aot. Json and delete about.module in the files array, assuming that you dont have about.module in your angular app folder

**Comment by sharifnascenia** [comment]
i have solved it by changing genDir in **tsconfig-aot.json**   to wwwroot

 "angularCompilerOptions": {
    "genDir": "wwwroot",
    "skipMetadataEmit": true
  },

and also **webpack.prod.js** by changing genDir to ./

...
 module: {
        rules: [
            {
                test: /\.ts$/,
                loaders: [
                    'awesome-typescript-loader',
                    'angular-router-loader?aot=true&genDir=./'
                ]
            }
          ....

And production build was ok .Thanks all

**Comment by damienbod** [comment]
@sharifnascenia thanks
