### ISSUE TITLE
Add frontend config files to config folder

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#84]
Roberto created a config folder in the root of the project, and added there webpack.test.js file used by Karma to build the test and spec.bundle.js that contains its context: 

Move other configuration files in this folder, because they are growing...

**Comment by damienbod** [comment]
https://github.com/damienbod/AngularWebpackVisualStudio/issues/31

**Comment by FabianGosebrink** [comment]
Can't we close this with Roberto's check in?
