### ISSUE TITLE
Karma debugging

### ISSUE THREAD

**Issue by andyfurniss4** [damienbod/AngularWebpackVisualStudio#85]
Just trying to get started with testing with Jasmine and Karma but have hit a problem and I'm struggling to figure out the cause.

Is there a way to debug with Karma in this project? I noticed that in the Angular testing docs (https://github.com/damienbod/AngularWebpackVisualStudio/issues) it states that you should be able to easily debug in the Console window by finding the test file however everything seems to be bundled here.

**Comment by robisim74** [comment]
This project uses webpack for building, including tests. However in the _config_ folder there is the _webpack.test.js_ file, that you can complete with the configurations your tests will need (not all equal), including the _source-map-loader_ that creates the _.map_ files to facilitate debugging as in _webpack.dev.js_ file.

Greetings

**Comment by andyfurniss4** [comment]
Thanks Roberto. I managed to solve my problem without this but I will keep this in mind going forward. Feel free to close.
