### ISSUE TITLE
Adding spec.ts-files in the folder of object which is tested

### ISSUE THREAD

**Issue by FabianGosebrink** [damienbod/AngularWebpackVisualStudio#86]
Due to styleguides the *.spec.ts file should be where the component/pipe/filter/whatever-to-test is

**Comment by robisim74** [comment]
If you continue to read the docs, you find:

>Application integration specs can test the interactions of multiple parts spread across folders and modules. They don't really belong to any part in particular, so they don't have a natural home next to any one file.

>It's often better to create an appropriate folder for them in the tests directory.

In our case, we are also testing the services that call the backend, so it is more appropriate to call them _integration tests_. In any case, everyone can place the tests where they want (the configuration reads all _angularApp_ tests).

**Comment by FabianGosebrink** [comment]
OKay, agree. Just thought of the modularity and that a part of the module itself is also a *.spec.ts file. Copy/Pasting the module (which is placed in the folder) would be incomplete when the test is not copied, too. However, totally agree that *.spec.ts files can be placed where it fits best. Integration & Unit tests should be treaten different: I personally take that with me :) Like it.

**Comment by robisim74** [comment]
np Fabian: if the home component did not recall other services (becoming a _test case_), I would place its _*.spec.ts_ next to it. However in Angular the difference between unit and integration tests is not always well defined. I think it's important just to provide a configuration, and then everyone can be free to use his style.
