### ISSUE TITLE
direct client deep navigation doesn't work

### ISSUE THREAD

**Issue by ralfe-software** [damienbod/AngularWebpackVisualStudio#88]
The provided solution works so far for my needs - thanks for this!

So far what I observed. After starting the application I can use without problems the Angular navigation.
But directly accessing, say /about isn't possible. 

I know so far that the routing is the core problem. Personally everything that starts not with /api/something can be ignored from an MVC perspective. The issue is I din't find a way to express so far returning the index.html and still keep the original query path (e.g. '/about') and Angular router does it's job.

Has somebody already solved the problem?

Thanks!

**Comment by damienbod** [comment]
This should work, I'll have a look. Was thinking of updating this routing setup using this example:

https://www.strathweb.com/2017/04/running-multiple-independent-asp-net-core-pipelines-side-by-side-in-the-same-application/

**Comment by ralfe-software** [comment]
Thanks for the quick reply and I retest again and it worked. Whatever went wrong yesterday, I can't reproduce it now.

Then this can be closed.

As a side note for improving, and maybe you have it already on your improvement list: If the routing works without to replicate the Angular routes on the server side would be very nice. Maybe https://github.com/aspnet/JavaScriptServices could also be an interesting part to improve the current routing setup.
