### ISSUE TITLE
publish to local iis-server

### ISSUE THREAD

**Issue by j-nord** [damienbod/AngularWebpackVisualStudio#89]
In the development environment it runs fine.

But when you publish the project to iis-server with webdeploy the paths are not set correctly.

Only "Loading...." on screen.

**Comment by damienbod** [comment]
Check the F12 in the browser, usually the angular app was not built correctly

> npm install
> npm run build-production

Greetings Damien

**Comment by j-nord** [comment]
We thought the creation with Webdeploy and publishing on the web server.

But now we have the actual version downloaded and the code runs no longer in Visual Studio 2017.

Would be nice if you would find a version on the Internet, which would work the same with the installation (npm install, npm run build-production, .. tested) and which could be published without error.

And it would be even nicer if you only exchange the app directory and controller and a few settings and it runs.

But that seems to be really difficult.

We do not give up hope.

Regards

j.nord

**Comment by FabianGosebrink** [comment]
Hey @j-nord ,

what does the console say if you hit F12 on the server when the "Loading..." is displayed?

BR

**Comment by j-nord** [comment]
error message under visual studio 2017:
website not found: http://localhost:5000/indes.html

**Comment by FabianGosebrink** [comment]
Do you mean "index.html"?

**Comment by j-nord** [comment]
yes

Failed to load resource: the server responded with a status of 404 (Not Found) index.html

**Comment by damienbod** [comment]
@j-nord Seems like something is going wrong with the publish.  I just the dotnet publish and it would fine. This should work as clone, build, publish. I do all of this exxcept the publich on the appveyor server.

https://ci.appveyor.com/project/damienbod/angular2webpackvisualstudio

I publish using a npm script. This makes it possible to build the angular app first in production mode

https://github.com/damienbod/AngularWebpackVisualStudio/blob/master/src/AngularWebpackVisualStudio/package.json#L21

Usually VS2017 is configured incorrectly to build SPA apps, (per default) You might need to install the latest node and use this from VS2017.

Hope this helps

Greetings Damien

**Comment by CLYeo** [comment]
hi, i'm facing the similar issue

downloaded the package, changed nothing
build the package in npm and is able to run the page using F5 in visual studio

but when I publish it for production and set it up in IIS
it is showing 'Loading ...' on screen

please help

F12 + console
<a href="https://imgbb.com/"><img src="https://image.ibb.co/gG3GtF/error1.png" alt="error1" border="0"></a>

View source
<a href="https://ibb.co/h9D5na"><img src="https://preview.ibb.co/gjLUDF/error2.png" alt="error2" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'></a><br />

**Comment by CLYeo** [comment]
ok I found the solution to my previous comment

you cant deploy the website as a new 'application' in an existing website
you need to create a new 'website' with another port for it to work
