### ISSUE TITLE
Image Caching using hash

### ISSUE THREAD

**Issue by 7chandan** [damienbod/AngularWebpackVisualStudio#91]
Hello,

In prod webpack config you are using:
            {
                test: /\.(png|jpg|gif|woff|woff2|ttf|svg|eot)$/,
                loader: 'file-loader?name=assets/[name]-[hash:6].[ext]'
            },

and this too:
        new CopyWebpackPlugin([
            { from: './angularApp/images/*.*', to: 'assets/', flatten: true }
        ])
So, is there a way to reference hashed images in app bundle?

**Comment by FabianGosebrink** [comment]
So the images copied with the copywebpack plugin are referenced in the html. We are using those directly. Images which are incluede in code which webpack touches through the "import"-statement are processed with the file-loader. What exactly are you trying to reference?
