### ISSUE TITLE
Hot Module Replacement not working

### ISSUE THREAD

**Issue by Trapulo** [damienbod/AngularWebpackVisualStudio#92]
Hi,
I try to develop using HMR but it seems not working. I can start the Web app, it works, but if I change something in angular source nothing is updated and I need to stop and recompile.
Any idea?
thanks

**Comment by Trapulo** [comment]
It seems I may download the client from port 8080 when it served by webpack-dev-server and updated by HMR, and run WebApi backend from IIS with standard F5 debug. Is this right?

thanks

**Comment by robisim74** [comment]
Yes, _webpack-dev-server_ with HMR is served from _http://localhost:8080_: just run `npm start`.

Greetings
