### ISSUE TITLE
Adding external Libraries (i.e. Alertify)

### ISSUE THREAD

**Issue by mtwarowski** [damienbod/AngularWebpackVisualStudio#94]
I have more a generic question then a real issue. I'm trying to add an external library in this case alertify. I would like to be able to access it's global variable. 

So i'm probably looking to do something like 
import 'alertify';
declare var alertify: any;

and then 
alertify.error("some error");

To achive that i've added a path in the ventor file but it still doesn't seem to be picking it up. I can see the file in the dev tools in chrome.

**Comment by robisim74** [comment]
Easy way:

`const alertify = require('alertifyjs');`

Greetings

**Comment by FabianGosebrink** [comment]
If you installed it in the node_modules folder you can do an

```import * as alertify from 'alertify'```

and then you can access it normally in typescript.
