### ISSUE TITLE
Upgrade configuration

### ISSUE THREAD

**Issue by robisim74** [damienbod/AngularWebpackVisualStudio#95]
@damienbod @FabianGosebrink

I pushed a new branch: https://github.com/damienbod/AngularWebpackVisualStudio/tree/Upgrade_configuration

Changes:
- Switched to `@ngtools/webpack` plugin for AoT building: it seems to be stable now, and has several advantages, for example:
  - no need to run _ngc_ compiler from the command line
  - no need to add modules into _tsconfig-aot_ (it supports lazy loading)
  - _scss_ files can be used also as `styleUrls` into the components
- Moved webpack config files into config folder: #84
- Update packages & yarn: #93

If you like the new configuration, test it & merge it.

Greetings,
Roberto

**Comment by damienbod** [comment]
will try it out tonight thanks

**Comment by damienbod** [comment]
really cool! thanks
