### ISSUE TITLE
Tags, releases, templates

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#96]
@robisim74 @FabianGosebrink  Should we add a release versions, tags so that it's easier to download?

**Comment by robisim74** [comment]
Yes, it is a good idea. I think it would be important also to make the readme:
- remove the code (it is just a duplicate)
- list the features
- detailed usage instructions

**Comment by robisim74** [comment]
A great example: https://github.com/AngularClass/angular-starter

**Comment by FabianGosebrink** [comment]
Yeah, would definitely be a good thing.

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink

Updating the readme a little bit at a time, hopefully will get it good with time.  

A lot to do here still, (detailed usage instructions)

first release out, 1.0.0
